
MERGE INTO ATTR_TYPES USING DUAL ON (TYPE_ID = 1)
WHEN MATCHED THEN UPDATE  SET NAME = 'Text', DESCR = NULL
WHEN NOT MATCHED THEN INSERT (TYPE_ID, NAME, DESCR) VALUES
(1, 'Text', NULL);
MERGE INTO ATTR_TYPES USING DUAL ON (TYPE_ID = 2)
WHEN MATCHED THEN UPDATE  SET NAME = 'Number', DESCR = NULL
WHEN NOT MATCHED THEN INSERT (TYPE_ID, NAME, DESCR) VALUES
(2, 'Number', NULL);
MERGE INTO ATTR_TYPES USING DUAL ON (TYPE_ID = 3)
WHEN MATCHED THEN UPDATE  SET NAME = 'Reference', DESCR = NULL
WHEN NOT MATCHED THEN INSERT (TYPE_ID, NAME, DESCR) VALUES
(3, 'Reference', NULL);
MERGE INTO ATTR_TYPES USING DUAL ON (TYPE_ID = 4)
WHEN MATCHED THEN UPDATE  SET NAME = 'Date', DESCR = NULL
WHEN NOT MATCHED THEN INSERT (TYPE_ID, NAME, DESCR) VALUES
(4, 'Date', NULL);
MERGE INTO ATTR_TYPES USING DUAL ON (TYPE_ID = 5)
WHEN MATCHED THEN UPDATE  SET NAME = 'List', DESCR = NULL
WHEN NOT MATCHED THEN INSERT (TYPE_ID, NAME, DESCR) VALUES
(5, 'List', NULL);