

MERGE INTO ATTRIBUTES USING DUAL ON (ATTR_ID = 1)
WHEN MATCHED THEN UPDATE  SET NAME = 'Password', ATTR_TYPE_ID = 1, PROPERTIES = NULL, FLAGS = NULL
WHEN NOT MATCHED THEN INSERT (ATTR_ID, NAME, ATTR_TYPE_ID, PROPERTIES, FLAGS) VALUES
(1, 'Password', 1, NULL, NULL);
MERGE INTO ATTRIBUTES USING DUAL ON (ATTR_ID = 2)
WHEN MATCHED THEN UPDATE  SET NAME = 'E-mail', ATTR_TYPE_ID = 1, PROPERTIES = NULL, FLAGS = NULL
WHEN NOT MATCHED THEN INSERT (ATTR_ID, NAME, ATTR_TYPE_ID, PROPERTIES, FLAGS) VALUES
(2, 'E-mail', 1, NULL, NULL);