
MERGE INTO OBJECTS USING DUAL ON (OBJECT_ID = 1)
WHEN MATCHED THEN UPDATE  SET OBJECT_TYPE_ID = 1, NAME = 'Container For Users', ORDER_NUMBER = NULL, PARENT_ID = NULL, DESCRIPTION = 'Contain all users in application'
WHEN NOT MATCHED THEN INSERT (OBJECT_ID, OBJECT_TYPE_ID, NAME, ORDER_NUMBER, PARENT_ID, DESCRIPTION) VALUES
(1, 1, 'Container For Users', NULL, NULL, 'Contain all users in application');
MERGE INTO OBJECTS USING DUAL ON (OBJECT_ID = 2)
WHEN MATCHED THEN UPDATE  SET OBJECT_TYPE_ID = 1, NAME = 'Inventory', ORDER_NUMBER = NULL, PARENT_ID = NULL, DESCRIPTION = 'Inventory project contain physical resources'
WHEN NOT MATCHED THEN INSERT (OBJECT_ID, OBJECT_TYPE_ID, NAME, ORDER_NUMBER, PARENT_ID, DESCRIPTION) VALUES
(2, 1, 'Inventory', NULL, NULL, 'Inventory project contain physical resources');